### ISSUE TITLE
Reject vs Drop for proxy

### ISSUE THREAD

**Issue by sparshev** [cirruslabs/softnet#31]
Hello folks, I'm trying to modify softnet to allow VM's to only connect to host system without global net access (needed for image building). Do you know any way to Reject the packets instead of Dropping them?

I'm modifying: https://github.com/cirruslabs/softnet/blob/11910d85406a1052f9e3073339d73fd1704feb71/lib/proxy/vm.rs#L68 from `Some(())` to `None`, and it's working, but the curl process waiting instead of immediately return error... Worrying it's some kind of virtualization framework limitation...

**Comment by edigaryev** [comment]
Hello Sergei 👋 

>Do you know any way to Reject the packets instead of Dropping them?

As a quick work-around you can just remove the default route in the guest:

```
sudo route delete default
```

A proper way would be probably to return an ICMP message of type [Destination Unreachable](https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-codes-3).

However, this feels to me as an out-of-scope functionality for the Softnet, because in the default usage scenario only a very limited number packets will be dropped and this should have no effect on normal operation.

Another alternative you can try is to use the [`Host` networking](https://docs.rs/vmnet/latest/vmnet/mode/host/struct.Host.html) here:

https://github.com/cirruslabs/softnet/blob/f5a1b1cdbd6692407573c0a3ccddea114301fde2/lib/host.rs#L24

As a result of this, your guest machine will get no default route installed automatically via the DHCP.

**Comment by sparshev** [comment]
Thank you @edigaryev ! Your suggestion to use Host instead of Shared works much better! I would try to prepare a simple change to have an ability to switch between host and shared network from tart (most probably env variables should work just fine).

And for sure it's up to you - but if softnet will be able to provide isolation of the VM networking on demand, that will be a great addition for Tart, because all the major virtualization solutions allows to choose between hostonly and NAT networks.

**Comment by edigaryev** [comment]
Hello @sparshev 👋 

Do you rely on `--net-host` as a means of isolating the traffic between VMs, or that's not crucial for your use-case?

We have a request related to that in https://github.com/cirruslabs/softnet/issues/37, and I'm wondering if it would be OK to make the Softnet configure `--net-host` without intra-VM isolation as it is right now.

**Comment by rabits** [comment]
Hi @edigaryev , we're following "least privilege by default" principle so that will be great to have it available. If you want to change the defaults to "not private by default" - please make sure it's in the changelog with a huge warning and an option to enable it back, so the other folks will not suffer from security degradation (although probably will, but since the project is not that old - I think it's tolerable).

**Comment by edigaryev** [comment]
@rabits are you using `--net-host` specifically or just `--net-softnet`?

If it's the former, could you please explain your use-case a bit more, so we can better understand and devise/advise for an alternative.

Historical pre-text: the only reason currently have a `--net-host` flag in `tart run` is that there's no `VZHostOnlyNetworkDeviceAttachment` available in the [`Virtualization.Framework`](https://developer.apple.com/documentation/virtualization) yet.

We anticipate that in the future Apple will make it available, and the Softnet won't be needed at all, so all the restrictions currently imposed by the Softnet won't be in place.

**Comment by rabits** [comment]
Oh, sorry, yeah we're using `--net-host` for tart-cli packer plugin. The reason for that - is to make the image building isolated (sandboxed) from any remote service but host controller machine to keep the build process reproducible with no accidental external dependencies and influence.
